version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-spring2
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demodb
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: olnester-spring-boot:latest
    network_mode: bridge
    container_name: olnester-spring-boot
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres