app:
  datasource:
    jdbc-url: jdbc:postgresql://demodb.chd2hx0ozjuo.us-east-2.rds.amazonaws.com:5432/demodb
    username: postgres
    password: password
    pool-size: 30

  mssqlsource:
    jdbc-url: jdbc:sqlserver://chsitest.chd2hx0ozjuo.us-east-2.rds.amazonaws.com:1433;databaseName=demodb
    username: admin
    password: password
    pool-size: 30
